[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src/"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/api"
  VITE_ENV = "production"
  VITE_ENABLE_MOCK_API = "false"
  VITE_ENABLE_DEV_TOOLS = "false"
  VITE_FIREBASE_API_KEY = "AIzaSyDRXrPSmDwtLck9t2gpd6KfGJdGNAIG0to"
  VITE_FIREBASE_AUTH_DOMAIN = "ubox-manager.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "ubox-manager"
  VITE_FIREBASE_STORAGE_BUCKET = "ubox-manager.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "787932614915"
  VITE_FIREBASE_APP_ID = "1:787932614915:web:252ff9fe364177824a9936"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.cloudfunctions.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.firebaseio.com https://*.cloudfunctions.net https://*.googleapis.com wss://*.firebaseio.com;"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true